/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HistoryEntry {
  'timestamp' : Time,
  'aiResponse' : string,
  'ingredients' : Array<string>,
}
export interface Recipe {
  'id' : bigint,
  'name' : string,
  'steps' : Array<string>,
  'ingredients' : Array<string>,
}
export type Time = bigint;
export interface Utensil {
  'id' : bigint,
  'name' : string,
  'size' : string,
  'type' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addHistoryEntry' : ActorMethod<[Array<string>, string], undefined>,
  'addRecipe' : ActorMethod<[string, Array<string>, Array<string>], bigint>,
  'addUtensil' : ActorMethod<[string, string, string], bigint>,
  'deleteRecipe' : ActorMethod<[bigint], undefined>,
  'deleteUtensil' : ActorMethod<[bigint], undefined>,
  'getHistory' : ActorMethod<[], Array<HistoryEntry>>,
  'getRecipe' : ActorMethod<[bigint], Recipe>,
  'getUserRecipes' : ActorMethod<[], Array<Recipe>>,
  'getUserUtensils' : ActorMethod<[], Array<Utensil>>,
  'getUtensil' : ActorMethod<[bigint], Utensil>,
  'updateUtensil' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];